/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HotelRouteImport } from './routes/hotel'
import { Route as HotelIndexRouteImport } from './routes/hotel.index'
import { Route as HotelApplicationsRouteImport } from './routes/hotel.applications'
import { Route as HotelCampaignsRouteImport } from './routes/hotel.campaigns'
import { Route as HotelInsightsRouteImport } from './routes/hotel.insights'
import { Route as HotelMessagesRouteImport } from './routes/hotel.messages'
import { Route as HotelSettingsRouteImport } from './routes/hotel.settings'
import { Route as HotelStaysRouteImport } from './routes/hotel.stays'
import { Route as HotelApplicationsCreatorIdRouteImport } from './routes/hotel.applications_.$creatorId'
import { Route as HotelSettingsIndexRouteImport } from './routes/hotel.settings.index'
import { Route as HotelSettingsAccountRouteImport } from './routes/hotel.settings.account'
import { Route as HotelSettingsGalleryRouteImport } from './routes/hotel.settings.gallery'
import { Route as HotelSettingsProfileRouteImport } from './routes/hotel.settings.profile'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelRoute = HotelRouteImport.update({
  id: '/hotel',
  path: '/hotel',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelIndexRoute = HotelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HotelRoute,
} as any)
const HotelApplicationsRoute = HotelApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => HotelRoute,
} as any)
const HotelCampaignsRoute = HotelCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => HotelRoute,
} as any)
const HotelInsightsRoute = HotelInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => HotelRoute,
} as any)
const HotelMessagesRoute = HotelMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => HotelRoute,
} as any)
const HotelSettingsRoute = HotelSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => HotelRoute,
} as any)
const HotelStaysRoute = HotelStaysRouteImport.update({
  id: '/stays',
  path: '/stays',
  getParentRoute: () => HotelRoute,
} as any)
const HotelApplicationsCreatorIdRoute =
  HotelApplicationsCreatorIdRouteImport.update({
    id: '/applications_/$creatorId',
    path: '/applications/$creatorId',
    getParentRoute: () => HotelRoute,
  } as any)
const HotelSettingsIndexRoute = HotelSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HotelSettingsRoute,
} as any)
const HotelSettingsAccountRoute = HotelSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => HotelSettingsRoute,
} as any)
const HotelSettingsGalleryRoute = HotelSettingsGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => HotelSettingsRoute,
} as any)
const HotelSettingsProfileRoute = HotelSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => HotelSettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hotel': typeof HotelRouteWithChildren
  '/hotel/applications': typeof HotelApplicationsRoute
  '/hotel/campaigns': typeof HotelCampaignsRoute
  '/hotel/insights': typeof HotelInsightsRoute
  '/hotel/messages': typeof HotelMessagesRoute
  '/hotel/settings': typeof HotelSettingsRouteWithChildren
  '/hotel/stays': typeof HotelStaysRoute
  '/hotel/': typeof HotelIndexRoute
  '/hotel/applications/$creatorId': typeof HotelApplicationsCreatorIdRoute
  '/hotel/settings/account': typeof HotelSettingsAccountRoute
  '/hotel/settings/gallery': typeof HotelSettingsGalleryRoute
  '/hotel/settings/profile': typeof HotelSettingsProfileRoute
  '/hotel/settings/': typeof HotelSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hotel/applications': typeof HotelApplicationsRoute
  '/hotel/campaigns': typeof HotelCampaignsRoute
  '/hotel/insights': typeof HotelInsightsRoute
  '/hotel/messages': typeof HotelMessagesRoute
  '/hotel/stays': typeof HotelStaysRoute
  '/hotel': typeof HotelIndexRoute
  '/hotel/applications/$creatorId': typeof HotelApplicationsCreatorIdRoute
  '/hotel/settings/account': typeof HotelSettingsAccountRoute
  '/hotel/settings/gallery': typeof HotelSettingsGalleryRoute
  '/hotel/settings/profile': typeof HotelSettingsProfileRoute
  '/hotel/settings': typeof HotelSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hotel': typeof HotelRouteWithChildren
  '/hotel/applications': typeof HotelApplicationsRoute
  '/hotel/campaigns': typeof HotelCampaignsRoute
  '/hotel/insights': typeof HotelInsightsRoute
  '/hotel/messages': typeof HotelMessagesRoute
  '/hotel/settings': typeof HotelSettingsRouteWithChildren
  '/hotel/stays': typeof HotelStaysRoute
  '/hotel/': typeof HotelIndexRoute
  '/hotel/applications_/$creatorId': typeof HotelApplicationsCreatorIdRoute
  '/hotel/settings/account': typeof HotelSettingsAccountRoute
  '/hotel/settings/gallery': typeof HotelSettingsGalleryRoute
  '/hotel/settings/profile': typeof HotelSettingsProfileRoute
  '/hotel/settings/': typeof HotelSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hotel'
    | '/hotel/applications'
    | '/hotel/campaigns'
    | '/hotel/insights'
    | '/hotel/messages'
    | '/hotel/settings'
    | '/hotel/stays'
    | '/hotel/'
    | '/hotel/applications/$creatorId'
    | '/hotel/settings/account'
    | '/hotel/settings/gallery'
    | '/hotel/settings/profile'
    | '/hotel/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hotel/applications'
    | '/hotel/campaigns'
    | '/hotel/insights'
    | '/hotel/messages'
    | '/hotel/stays'
    | '/hotel'
    | '/hotel/applications/$creatorId'
    | '/hotel/settings/account'
    | '/hotel/settings/gallery'
    | '/hotel/settings/profile'
    | '/hotel/settings'
  id:
    | '__root__'
    | '/'
    | '/hotel'
    | '/hotel/applications'
    | '/hotel/campaigns'
    | '/hotel/insights'
    | '/hotel/messages'
    | '/hotel/settings'
    | '/hotel/stays'
    | '/hotel/'
    | '/hotel/applications_/$creatorId'
    | '/hotel/settings/account'
    | '/hotel/settings/gallery'
    | '/hotel/settings/profile'
    | '/hotel/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HotelRoute: typeof HotelRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel': {
      id: '/hotel'
      path: '/hotel'
      fullPath: '/hotel'
      preLoaderRoute: typeof HotelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel/': {
      id: '/hotel/'
      path: '/'
      fullPath: '/hotel/'
      preLoaderRoute: typeof HotelIndexRouteImport
      parentRoute: typeof HotelRoute
    }
    '/hotel/applications': {
      id: '/hotel/applications'
      path: '/applications'
      fullPath: '/hotel/applications'
      preLoaderRoute: typeof HotelApplicationsRouteImport
      parentRoute: typeof HotelRoute
    }
    '/hotel/campaigns': {
      id: '/hotel/campaigns'
      path: '/campaigns'
      fullPath: '/hotel/campaigns'
      preLoaderRoute: typeof HotelCampaignsRouteImport
      parentRoute: typeof HotelRoute
    }
    '/hotel/insights': {
      id: '/hotel/insights'
      path: '/insights'
      fullPath: '/hotel/insights'
      preLoaderRoute: typeof HotelInsightsRouteImport
      parentRoute: typeof HotelRoute
    }
    '/hotel/messages': {
      id: '/hotel/messages'
      path: '/messages'
      fullPath: '/hotel/messages'
      preLoaderRoute: typeof HotelMessagesRouteImport
      parentRoute: typeof HotelRoute
    }
    '/hotel/settings': {
      id: '/hotel/settings'
      path: '/settings'
      fullPath: '/hotel/settings'
      preLoaderRoute: typeof HotelSettingsRouteImport
      parentRoute: typeof HotelRoute
    }
    '/hotel/stays': {
      id: '/hotel/stays'
      path: '/stays'
      fullPath: '/hotel/stays'
      preLoaderRoute: typeof HotelStaysRouteImport
      parentRoute: typeof HotelRoute
    }
    '/hotel/applications_/$creatorId': {
      id: '/hotel/applications_/$creatorId'
      path: '/applications/$creatorId'
      fullPath: '/hotel/applications/$creatorId'
      preLoaderRoute: typeof HotelApplicationsCreatorIdRouteImport
      parentRoute: typeof HotelRoute
    }
    '/hotel/settings/': {
      id: '/hotel/settings/'
      path: '/'
      fullPath: '/hotel/settings/'
      preLoaderRoute: typeof HotelSettingsIndexRouteImport
      parentRoute: typeof HotelSettingsRoute
    }
    '/hotel/settings/account': {
      id: '/hotel/settings/account'
      path: '/account'
      fullPath: '/hotel/settings/account'
      preLoaderRoute: typeof HotelSettingsAccountRouteImport
      parentRoute: typeof HotelSettingsRoute
    }
    '/hotel/settings/gallery': {
      id: '/hotel/settings/gallery'
      path: '/gallery'
      fullPath: '/hotel/settings/gallery'
      preLoaderRoute: typeof HotelSettingsGalleryRouteImport
      parentRoute: typeof HotelSettingsRoute
    }
    '/hotel/settings/profile': {
      id: '/hotel/settings/profile'
      path: '/profile'
      fullPath: '/hotel/settings/profile'
      preLoaderRoute: typeof HotelSettingsProfileRouteImport
      parentRoute: typeof HotelSettingsRoute
    }
  }
}

interface HotelSettingsRouteChildren {
  HotelSettingsAccountRoute: typeof HotelSettingsAccountRoute
  HotelSettingsGalleryRoute: typeof HotelSettingsGalleryRoute
  HotelSettingsProfileRoute: typeof HotelSettingsProfileRoute
  HotelSettingsIndexRoute: typeof HotelSettingsIndexRoute
}

const HotelSettingsRouteChildren: HotelSettingsRouteChildren = {
  HotelSettingsAccountRoute: HotelSettingsAccountRoute,
  HotelSettingsGalleryRoute: HotelSettingsGalleryRoute,
  HotelSettingsProfileRoute: HotelSettingsProfileRoute,
  HotelSettingsIndexRoute: HotelSettingsIndexRoute,
}

const HotelSettingsRouteWithChildren = HotelSettingsRoute._addFileChildren(
  HotelSettingsRouteChildren,
)

interface HotelRouteChildren {
  HotelApplicationsRoute: typeof HotelApplicationsRoute
  HotelCampaignsRoute: typeof HotelCampaignsRoute
  HotelInsightsRoute: typeof HotelInsightsRoute
  HotelMessagesRoute: typeof HotelMessagesRoute
  HotelSettingsRoute: typeof HotelSettingsRouteWithChildren
  HotelStaysRoute: typeof HotelStaysRoute
  HotelIndexRoute: typeof HotelIndexRoute
  HotelApplicationsCreatorIdRoute: typeof HotelApplicationsCreatorIdRoute
}

const HotelRouteChildren: HotelRouteChildren = {
  HotelApplicationsRoute: HotelApplicationsRoute,
  HotelCampaignsRoute: HotelCampaignsRoute,
  HotelInsightsRoute: HotelInsightsRoute,
  HotelMessagesRoute: HotelMessagesRoute,
  HotelSettingsRoute: HotelSettingsRouteWithChildren,
  HotelStaysRoute: HotelStaysRoute,
  HotelIndexRoute: HotelIndexRoute,
  HotelApplicationsCreatorIdRoute: HotelApplicationsCreatorIdRoute,
}

const HotelRouteWithChildren = HotelRoute._addFileChildren(HotelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HotelRoute: HotelRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
